### ISSUE TITLE
추억 새기기 image 처리 추가

### ISSUE THREAD

**Issue by HubCreator** [keepsaker/back-memory#12]
### ⏰ Estimated Time

2

### 🛠️ Description

추억을 새길 때 image를 처리할 수 있도록 Controller를 수정한다.

### ✅ Tasks

- [x] image를 컨트롤러에서 처리
- [x] 서비스에서 이미지에 대한 좌표 추출
- [x] 이미지와 좌표 정보 영속화
